---

random_seed: 0
federated_epochs: 3
local_epochs: 1
num_clients: 4
batch_size: 128
server_validation_size: 0.2

flwr:
  num_clients_per_round_fit: ${num_clients}
  num_clients_per_round_eval: ${num_clients}

config_fit:
  random_seed: 0
  federated_epochs: ${federated_epochs}
  num_clients: ${num_clients}
  batch_size: ${batch_size}
  local_epochs: ${local_epochs}
  lr: 0.001
  momentum: 0.9
  patience: 10
  validation_size: 0.2
  weight_decay: 0.1

defaults:
  - client_fn: dcph
  - evaluate_fn: dcph
  - fit_config_fn: dcph
  - model: dcph
  - model_fn: dcph
  - init_params: dcph
  - strategy: fedavg
  - dataset_fn: dcph_support
  - _self_

utils:
  logs:
    loguru: true
    log_level: INFO
