---

_target_: flwr.server.strategy.FedAvg
fraction_fit: 0.00001
min_fit_clients: ${flwr.num_clients_per_round_fit}
fraction_evaluate: 0.00001
min_evaluate_clients: ${flwr.num_clients_per_round_eval}
min_available_clients: ${num_clients}
on_fit_config_fn: ${fit_config_fn}