---

federated_epochs: 3
local_epochs: 1
num_clients: 4
batch_size: 256
random_seed: 42
server_validation_size: 0.2

flwr:
  num_clients_per_round_fit: 4
  num_clients_per_round_eval: 4

config_fit:
  federated_epochs: ${federated_epochs}
  num_clients: ${num_clients}
  batch_size: ${batch_size}
  local_epochs: ${local_epochs}
  lr: 0.001
  momentum: 0.9
  patience: 10
  validation_size: 0.2
  random_seed: 0
  weight_decay: 0.01

defaults:
  - model: dcph
  - model_impl: dcph
  - strategy: fedavg

utils:
  logs:
    loguru: true
    log_level: INFO
